name: fav
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.6
  badges: ^3.0.2  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rajdhani
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
        - asset: fonts/Rajdhani-Bold.ttf
          weight: 700
          style: italic
